export const TEAM_DATA = [
  {
    name: "Nelson Madiba Amo",
    title: "President",
    hoverTitle: "President",
    imagePosition: "center -15%",
    location: "Accra, Ghana",
    bio: `Nelson Amo is business growth expert with experience across several African countries and sectors. 

He is the President of FarmGate Africa, Founder and Executive Director of Innohub Foundation, an enterprise support organization that supports Small and Growing Businesses (SGBs) to pursue scale and impact. Innohub supports businesses that demonstrate clear impact along the triple bottom-line: PEOPLE, PLANET AND SHARED PROSPERITY. 

Since 2015, he has led the Innohub team to design and execute diverse business scaling projects across various industries. He served as Grant Manager for the $3.2m Ghana Climate Venture Facility with funding from the World Bank, leading to the set-up of a climate focused SME fund and a technical assistance program to support the growth of SMEs in the climate and green sectors. Nelson has led the Innohub team to design and manage impactful projects such as the Tullow Agriventures program (with $1.6m funding from Tullow Ghana Limited), MTN Enterprise Support Program (with Gh9m of funding commitment from MTN Ghana Foundation), among several others. 


Nelson has also led consulting projects across several industries including health, medical drones, renewable energy, agribusiness, and sits on the boards of several businesses.  

Nelson is an alumnus of the Oxford Social Finance Program from the Oxford University Said Business School and holds a Certificate in “Development Programme in Entrepreneurship” from the Leeds University Business School. He also has an MSc. in Development Studies from LSE, with a special interest in Business Model Innovation at the bottom of the Pyramid. Nelson holds a certificate in “Unlocking Finance for Emerging Markets and Developing Economies”, a World Bank course, as well as a certificate in “Startup Accelerators in the Entrepreneurial Ecosystem” from the Golda Meir MASHAV Carmel International Training Center in Israel.

Nelson is driven by the passion to promote social innovation and enterprising solutions to poverty and underdevelopment.`,
    photoUrl: "/images/nelson modal.webp",
    photoUrlModal: "/images/nelson.webp",
    email: "",
    socialLinks: { linkedin: "https://linkedin.com" },
    department: "Leadership & Governance",
    order: 9,
  },
  {
    name: "Emmanuel Galley Baiden",
    title: "VP, Investment & Strategy",
    hoverTitle: "Farmer",
    imagePosition: "center -15%",
    location: "Accra, Ghana",
    bio: `Emmanuel is an enthusiatic farmer and a business executive professional with over a decade of extensive expertise in agribusiness, financial leadership, business development, strategy execution and project management. He provides finance specialist, business partnering and advisory support for major grants and impact-focused projects across Africa and beyond including a $3.2 million World Bank SGB Climate Investment Fund, a $2.0 million eTransform mLab GoG initiative sponsored by the World Bank, and has also managed many key enterprise support programs across Ghana such as the $1.6 million Tullow Agriventure Program (TAP), and the GHS 6.33 million ESO program by MTN Ghana Foundation. Emmanuel is a Chartered Accountant and a Risk Management Specialist. He also holds an MSc in Accounting and Finance from UGBS.`,
    photoUrl: "/images/Emanuel Galley Baiden.webp",
    photoUrlModal: "/images/Emanuel Galley Baiden modal.webp",
    email: "",
    socialLinks: { linkedin: "https://linkedin.com" },
    department: "Leadership & Governance",
    order: 8,
  },
  {
    name: "Rachael Effah-Frempah",
    title: "Chief Financial Officer | CFO",
    hoverTitle: "CFO",
    location: "Accra, Ghana",
    bio: "Rachael is a skilled finance professional with expertise in strategic financial planning, analysis, and grant management. She excels in delivering financial insights and driving process improvements to support business growth. Before FGAI, she provides key financial management and administration support at Innohub. She also worked as a Finance Officer at GHIPSS, handling accounts receivable. Rachael holds a BSc in Banking and Finance from UGBS and is a Chartered Accountant from ACCA.",
    photoUrl: "/images/Rachael Effah-Frempah.webp",
    photoUrlModal: "/images/Rachael Effah-Frempah modal.webp",
    email: "",
    socialLinks: { linkedin: "" },
    department: "Leadership & Governance",
    order: 3,
  },
  {
    name: "Linda Amankwah",
    title: "Strategic Advisor, Talent Capital & Culture",
    hoverTitle: "Advisor",
    imagePosition: "center -15%",
    location: "Accra, Ghana",
    bio: "Linda is an HR professional with experience in banking, insurance, and non-profit sectors. She has successfully managed projects in organizational restructuring and talent acquisition as an Associate Consultant at Excel HR Consult. Linda holds an MBA in Human Resource Management and a Bachelor’s in English and Psychology from the University of Ghana.",
    photoUrl: "/images/Linda Amankwah.webp",
    photoUrlModal: "/images/Linda Amankwah modal.webp",
    email: "",
    socialLinks: { linkedin: "https://linkedin.com" },
    department: "Strategic Advisors",
    order: 4,
  },
  {
    name: "Jude Appoh Obeng",
    title: "Telemarketer",
    hoverTitle: "Telemarketer",
    location: "Accra, Ghana",
    bio: "Jude is a dedicated telemarketer with a strong background in customer service and sales. He brings a wealth of experience in engaging with clients and promoting FarmGate Africa's services.",
    photoUrl: "/images/Jude Appoh Obeng.webp",
    photoUrlModal: "/images/Jude Appoh Obeng modal.webp",
    email: "",
    socialLinks: { linkedin: "https://linkedin.com" },
    department: "General Management",
    order: 1,
  },
  {
    name: "Amy Nana Ama Kumatey",
    title: "Comms & Brand Strategy",
    hoverTitle: "Comms",
    location: "Accra, Ghana",
    bio: "Nana is a communications and brand strategy expert with a background in marketing and public relations. She brings a wealth of experience in developing and executing brand strategies that resonate with diverse audiences.",
    photoUrl: "/images/Nana Ama.webp",
    photoUrlModal: "/images/Nana Ama modal.webp",
    email: "",
    socialLinks: { linkedin: "https://linkedin.com" },
    department: "General Management",
    order: 2,
  },
  {
    name: "Nicholson Eben Atsoribo",
    title: "Agronomist & Operations",
    location: "Accra, Ghana",
    bio: "Nicholson is an agronomist and operations specialist with extensive experience in agricultural research and development. He has led multiple projects in crop management, soil health, and sustainable farming practices.",
    photoUrl: "/images/Nicholson Eben Atsoribo.webp",
    photoUrlModal: "/images/Nicholson Eben Atsoribo modal.webp",
    email: "",
    socialLinks: { linkedin: "https://linkedin.com" },
    department: "Operations Management",
    order: 4,
  },
  {
    name: "Nancy Otibo Tamakoe",
    title: "Strategic Advisor, Soil & Crop",
    hoverTitle: "Advisor",
    location: "Accra, Ghana",
    bio: "Nancy is a strategic advisor specializing in soil and crop management. She brings deep expertise in sustainable agriculture and has led initiatives to improve soil health and crop yields across various farming systems.",
    photoUrl: "/images/Nancy Otibo Tamakoe .webp",
    photoUrlModal: "/images/Nancy Otibo Tamakoe modal.webp",
    email: "",
    socialLinks: { linkedin: "https://linkedin.com" },
    department: "Strategic Advisors",
    order: 7,
  },
  {
    name: "Jacob Korley",
    title: "Accounts Officer",
    location: "Accra, Ghana",
    bio: "Jacob is an experienced accounts officer with a strong background in financial management and accounting. He has successfully managed financial operations for various organizations, ensuring compliance and accuracy in all financial reporting.",
    photoUrl: "/images/Jacob Korley .webp",
    photoUrlModal: "/images/Jacob Korley modal.webp",
    email: "",
    socialLinks: { linkedin: "https://linkedin.com" },
    department: "Operations Management",
    order: 6,
  },
  {
    name: "Elizabeth Dadzie",
    title: "Field Sales Executive",
    hoverTitle: "Sales",
    location: "Accra, Ghana",
    bio: "Lizzy is a committed field sales rep with excellent background in customer relations service and boosting sale. She brings valuable field experience in engaging clients and driving sales at FarmGate Africa.",
    photoUrl: "/images/Elizabeth-Dadzie.webp",
    photoUrlModal: "/images/Elizabeth-Dadzie-modal.webp",
    imagePosition: "center -15%",
    email: "",
    socialLinks: { linkedin: "https://linkedin.com" },
    department: "Operations Management",
    order: 6,
  },
  {
    name: "David Ndanu",
    title: "CTO, Advisor",
    hoverTitle: "Advisor",
    location: "Accra, Ghana",
    bio: "David Ndanu is a Software Engineer and Systems Architect with over 7 years of experience building enterprise platforms and scalable digital solutions across multiple industries. He currently serves as the Chief Technology Officer at FarmGate Africa, where he leads the design and development of data-driven systems aimed at improving agricultural operations and productivity.With a strong background in building ERP systems, financial platforms, and operational tools used by real businesses, David focuses on creating practical solutions that support decision-making and efficiency. His work combines software engineering with a growing interest in data systems and emerging geospatial applications within agriculture.At Farmgate, he is committed to developing technology that empowers farmers, improves resource management, and supports the long-term growth of agriculture across Africa.",
    photoUrl: "/images/David-Ndanu-modal.webp",
    photoUrlModal: "/images/David-Ndanu.webp",
    imagePosition: "center -15%",
    email: "",
    socialLinks: { linkedin: "https://linkedin.com" },
    department: "Strategic Advisors",
    order: 6,
  },
  {
    name: "Kow Aboagye-Ghunney",
    title: "Chief Crop Production Officer | CCPO",
    hoverTitle: "CCPO",
    location: "Accra, Ghana",
    bio: "Kow Aboagye-Ghunney is a seasoned agricultural professional with extensive experience in crop production and management. A distinguished Fulbright Scholar, he brings a wealth of knowledge and expertise to his role as Chief Crop Production Officer at FarmGate Africa, where he leads initiatives to enhance crop yields and promote sustainable farming practices. He is also the Director of Horticulture for FarmGate Africa & Industries.His commitment to driving agricultural advancement has been recognized with the Young Innovators Award in the agriculture category by the Springboard Foundation and Mastercard. Additionally, Kow was named the Best Innovative Farmer at the 41st National Farmers' Day. His deep background in agricultural science and his proven track record of innovation make him a valuable asset to the FarmGate team.",
    photoUrl: "/images/kow-aboagye.webp",
    photoUrlModal: "/images/kow-aboagye-modal.webp",
    imagePosition: "center -15%",
    email: "",
    socialLinks: { linkedin: "https://linkedin.com" },
    department: "Leadership & Governance",
    order: 7,
  },
  {
    name: "Enoch Tetteh",
    title: "Chief Aqua-Production Officer | CAPO",
    hoverTitle: "CAPO",
    location: "Accra, Ghana",
    bio: "Enoch Tetteh is a professional aquaculture specialist with expertise in catfish and tilapia production, sustainable fish farming, and aquaculture management. As Chief Aqua-Production Officer (CAPO) at FarmGate Africa, he leads initiatives focused on improving aquatic productivity, fish health management, and efficient farming systems. He also doubles as Director of Aquaculture for FarmGate Africa & Industries.With certifications in Animal Health in Fish, Lean Management, and Financial Management in Aquaculture, Enoch combines technical expertise with practical business strategies to drive sustainable and profitable fish production. He is skilled in biosecurity protocols, cage and tank construction, water quality management, feed optimization, and operational efficiency.His commitment to innovation, healthy stock management, and data-driven aquaculture practices continues to make him a valuable asset to the FarmGate Africa team and the broader agricultural industry.",
    photoUrl: "/images/profile.webp",
    photoUrlModal: "/images/profile.webp",
    imagePosition: "center -15%",
    email: "",
    socialLinks: { linkedin: "https://linkedin.com" },
    department: "Leadership & Governance",
    order: 7,
  },

  {
    name: "Juliet Yayra Dzasi",
    title: "GM, Chief Farmer",
    hoverTitle: "Chief Farmer",
    location: "Accra, Ghana",
    bio: "Juliet is an accomplished agripreneur and the General Manager of FarmGate Africa. Known as our Chief Farmer, she brings a strong academic and professional background to her leadership, holding an MSc in Development Management from the Kwame Nkrumah University of Science and Technology, a BA in Rural Development from Wisconsin International University College, and an Executive Certificate in Business Administration from Accra Business School. She spearheads FarmGate Africa’s mission to drive agricultural innovation and promote sustainable farming practices across the region. With a passion for food security and a deep understanding of market dynamics, Juliet leads the company’s teams in developing cutting-edge solutions that empower farmers, enhance productivity, and foster long-term growth in the agricultural sector.",
    photoUrl: "/images/Juliet-Yayra-Dzasi.webp",
    photoUrlModal: "/images/Juliet-Yayra-Dzasi-modal.webp",
    imagePosition: "center -15%",
    email: "",
    socialLinks: { linkedin: "https://linkedin.com" },
    department: "Leadership & Governance",
    order: 6,
  },
];
