export const TEAM_DATA = [
  {
    name: "Nelson Madiba Amo",
    title: "President",
    hoverTitle: "President",
    location: "Accra, Ghana",
    bio: `Nelson is a seasoned business executive with over 15 years of experience in the agricultural sector. He has a proven track record of leading successful agribusiness ventures and driving sustainable growth. Nelson holds an MBA from the University of Ghana Business School and has been instrumental in shaping the strategic direction of FarmGate Africa.`,
    photoUrl: "/images/nelson.webp",
    photoUrlModal: "/images/nelson modal.webp",
    email: "",
    socialLinks: { linkedin: "https://linkedin.com" },
    department: "Leadership & Governance",
    order: 9,
  },
  {
    name: "Emmanuel Galley Baiden",
    title: "VP, Investment & Strategy",
    hoverTitle: "Farmer",
    location: "Accra, Ghana",
    bio: `Emmanuel is an enthusiatic farmer and a business executive professional with over a decade of extensive expertise in agribusiness, financial leadership, business development, strategy execution and project management. He provides finance specialist, business partnering and advisory support for major grants and impact-focused projects across Africa and beyond including a $3.2 million World Bank SGB Climate Investment Fund, a $2.0 million eTransform mLab GoG initiative sponsored by the World Bank, and has also managed many key enterprise support programs across Ghana such as the $1.6 million Tullow Agriventure Program (TAP), and the GHS 6.33 million ESO program by MTN Ghana Foundation. Emmanuel is a Chartered Accountant and a Risk Management Specialist. He also holds an MSc in Accounting and Finance from UGBS.`,
    photoUrl: "/images/Emanuel Galley Baiden.webp",
    photoUrlModal: "/images/Emanuel Galley Baiden modal.webp",
    email: "",
    socialLinks: { linkedin: "https://linkedin.com" },
    department: "Leadership & Governance",
    order: 8,
  },
  {
    name: "Rachael Effah-Frempah",
    title: "CFO, Chief Financial Officer",
    hoverTitle: "CFO",
    location: "Accra, Ghana",
    bio: "Rachael is a skilled finance professional with expertise in strategic financial planning, analysis, and grant management. She excels in delivering financial insights and driving process improvements to support business growth. Before FGAI, she provides key financial management and administration support at Innohub. She also worked as a Finance Officer at GHIPSS, handling accounts receivable. Rachael holds a BSc in Banking and Finance from UGBS and is a Chartered Accountant from ACCA.",
    photoUrl: "/images/Rachael Effah-Frempah.webp",
    photoUrlModal: "/images/Rachael Effah-Frempah modal.webp",
    email: "",
    socialLinks: { linkedin: "" },
    department: "Leadership & Governance",
    order: 3,
  },
  {
    name: "Linda Amankwah",
    title: "Strategic Advisor, Talent Capital & Culture",
    hoverTitle: "Advisor",
    location: "Accra, Ghana",
    bio: "Linda is an HR professional with experience in banking, insurance, and non-profit sectors. She has successfully managed projects in organizational restructuring and talent acquisition as an Associate Consultant at Excel HR Consult. Linda holds an MBA in Human Resource Management and a Bachelor’s in English and Psychology from the University of Ghana.",
    photoUrl: "/images/Linda Amankwah.webp",
    photoUrlModal: "/images/Linda Amankwah modal.webp",
    email: "",
    socialLinks: { linkedin: "https://linkedin.com" },
    department: "Strategic Advisors",
    order: 4,
  },
  {
    name: "Jude Appoh Obeng",
    title: "Telemarketer",
    hoverTitle: "Telemarketer",
    location: "Accra, Ghana",
    bio: "Jude is a dedicated telemarketer with a strong background in customer service and sales. He brings a wealth of experience in engaging with clients and promoting FarmGate Africa's services.",
    photoUrl: "/images/Jude Appoh Obeng.webp",
    photoUrlModal: "/images/Jude Appoh Obeng modal.webp",
    email: "",
    socialLinks: { linkedin: "https://linkedin.com" },
    department: "General Management",
    order: 1,
  },
  {
    name: "Amy Nana Ama Kumatey",
    title: "Comms & Brand Strategy",
    hoverTitle: "Comms",
    location: "Accra, Ghana",
    bio: "Nana is a communications and brand strategy expert with a background in marketing and public relations. She brings a wealth of experience in developing and executing brand strategies that resonate with diverse audiences.",
    photoUrl: "/images/Nana Ama.webp",
    photoUrlModal: "/images/Nana Ama modal.webp",
    email: "",
    socialLinks: { linkedin: "https://linkedin.com" },
    department: "General Management",
    order: 2,
  },
  {
    name: "Nicholson Eben Atsoribo",
    title: "Agronomist & Operations",
    location: "Accra, Ghana",
    bio: "Nicholson is an agronomist and operations specialist with extensive experience in agricultural research and development. He has led multiple projects in crop management, soil health, and sustainable farming practices.",
    photoUrl: "/images/Nicholson Eben Atsoribo.webp",
    photoUrlModal: "/images/Nicholson Eben Atsoribo modal.webp",
    email: "",
    socialLinks: { linkedin: "https://linkedin.com" },
    department: "Operations Management",
    order: 4,
  },
  {
    name: "Nancy Otibo Tamakoe",
    title: "Strategic Advisor, Soil & Crop",
    hoverTitle: "Advisor",
    location: "Accra, Ghana",
    bio: "Nancy is a strategic advisor specializing in soil and crop management. She brings deep expertise in sustainable agriculture and has led initiatives to improve soil health and crop yields across various farming systems.",
    photoUrl: "/images/Nancy Otibo Tamakoe .webp",
    photoUrlModal: "/images/Nancy Otibo Tamakoe modal.webp",
    email: "",
    socialLinks: { linkedin: "https://linkedin.com" },
    department: "Strategic Advisors",
    order: 7,
  },
  {
    name: "Jacob Korley",
    title: "Accounts Officer",
    location: "Accra, Ghana",
    bio: "Jacob is an experienced accounts officer with a strong background in financial management and accounting. He has successfully managed financial operations for various organizations, ensuring compliance and accuracy in all financial reporting.",
    photoUrl: "/images/Jacob Korley .webp",
    photoUrlModal: "/images/Jacob Korley modal.webp",
    email: "",
    socialLinks: { linkedin: "https://linkedin.com" },
    department: "Operations Management",
    order: 6,
  },
];
