export const TEAM_DATA = [
  {
    name: "Nelson Madiba Amo",
    title: "President",
    hoverTitle: "President",
    location: "Accra, Ghana",
    bio: `Nelson Amo is business growth expert with experience across several African countries and sectors. 

He is the President of FarmGate Africa, Founder and Executive Director of Innohub Foundation, an enterprise support organization that supports Small and Growing Businesses (SGBs) to pursue scale and impact. Innohub supports businesses that demonstrate clear impact along the triple bottom-line: PEOPLE, PLANET AND SHARED PROSPERITY. 

Since 2015, he has led the Innohub team to design and execute diverse business scaling projects across various industries. He served as Grant Manager for the $3.2m Ghana Climate Venture Facility with funding from the World Bank, leading to the set-up of a climate focused SME fund and a technical assistance program to support the growth of SMEs in the climate and green sectors. Nelson has led the Innohub team to design and manage impactful projects such as the Tullow Agriventures program (with $1.6m funding from Tullow Ghana Limited), MTN Enterprise Support Program (with Gh9m of funding commitment from MTN Ghana Foundation), among several others. 


Nelson has also led consulting projects across several industries including health, medical drones, renewable energy, agribusiness, and sits on the boards of several businesses.  

Nelson is an alumnus of the Oxford Social Finance Program from the Oxford University Said Business School and holds a Certificate in “Development Programme in Entrepreneurship” from the Leeds University Business School. He also has an MSc. in Development Studies from LSE, with a special interest in Business Model Innovation at the bottom of the Pyramid. Nelson holds a certificate in “Unlocking Finance for Emerging Markets and Developing Economies”, a World Bank course, as well as a certificate in “Startup Accelerators in the Entrepreneurial Ecosystem” from the Golda Meir MASHAV Carmel International Training Center in Israel.

Nelson is driven by the passion to promote social innovation and enterprising solutions to poverty and underdevelopment.`,
    photoUrl: "/images/nelson modal.webp",
    photoUrlModal: "/images/nelson.webp",
    email: "",
    socialLinks: { linkedin: "https://linkedin.com" },
    department: "Leadership & Governance",
    order: 9,
  },
  {
    name: "Emmanuel Galley Baiden",
    title: "VP, Investment & Strategy",
    hoverTitle: "Farmer",
    location: "Accra, Ghana",
    bio: `Emmanuel is an enthusiatic farmer and a business executive professional with over a decade of extensive expertise in agribusiness, financial leadership, business development, strategy execution and project management. He provides finance specialist, business partnering and advisory support for major grants and impact-focused projects across Africa and beyond including a $3.2 million World Bank SGB Climate Investment Fund, a $2.0 million eTransform mLab GoG initiative sponsored by the World Bank, and has also managed many key enterprise support programs across Ghana such as the $1.6 million Tullow Agriventure Program (TAP), and the GHS 6.33 million ESO program by MTN Ghana Foundation. Emmanuel is a Chartered Accountant and a Risk Management Specialist. He also holds an MSc in Accounting and Finance from UGBS.`,
    photoUrl: "/images/Emanuel Galley Baiden.webp",
    photoUrlModal: "/images/Emanuel Galley Baiden modal.webp",
    email: "",
    socialLinks: { linkedin: "https://linkedin.com" },
    department: "Leadership & Governance",
    order: 8,
  },
  {
    name: "Rachael Effah-Frempah",
    title: "CFO, Chief Financial Officer",
    hoverTitle: "CFO",
    location: "Accra, Ghana",
    bio: "Rachael is a skilled finance professional with expertise in strategic financial planning, analysis, and grant management. She excels in delivering financial insights and driving process improvements to support business growth. Before FGAI, she provides key financial management and administration support at Innohub. She also worked as a Finance Officer at GHIPSS, handling accounts receivable. Rachael holds a BSc in Banking and Finance from UGBS and is a Chartered Accountant from ACCA.",
    photoUrl: "/images/Rachael Effah-Frempah.webp",
    photoUrlModal: "/images/Rachael Effah-Frempah modal.webp",
    email: "",
    socialLinks: { linkedin: "" },
    department: "Leadership & Governance",
    order: 3,
  },
  {
    name: "Linda Amankwah",
    title: "Strategic Advisor, Talent Capital & Culture",
    hoverTitle: "Advisor",
    location: "Accra, Ghana",
    bio: "Linda is an HR professional with experience in banking, insurance, and non-profit sectors. She has successfully managed projects in organizational restructuring and talent acquisition as an Associate Consultant at Excel HR Consult. Linda holds an MBA in Human Resource Management and a Bachelor’s in English and Psychology from the University of Ghana.",
    photoUrl: "/images/Linda Amankwah.webp",
    photoUrlModal: "/images/Linda Amankwah modal.webp",
    email: "",
    socialLinks: { linkedin: "https://linkedin.com" },
    department: "Strategic Advisors",
    order: 4,
  },
  {
    name: "Jude Appoh Obeng",
    title: "Telemarketer",
    hoverTitle: "Telemarketer",
    location: "Accra, Ghana",
    bio: "Jude is a dedicated telemarketer with a strong background in customer service and sales. He brings a wealth of experience in engaging with clients and promoting FarmGate Africa's services.",
    photoUrl: "/images/Jude Appoh Obeng.webp",
    photoUrlModal: "/images/Jude Appoh Obeng modal.webp",
    email: "",
    socialLinks: { linkedin: "https://linkedin.com" },
    department: "General Management",
    order: 1,
  },
  {
    name: "Amy Nana Ama Kumatey",
    title: "Comms & Brand Strategy",
    hoverTitle: "Comms",
    location: "Accra, Ghana",
    bio: "Nana is a communications and brand strategy expert with a background in marketing and public relations. She brings a wealth of experience in developing and executing brand strategies that resonate with diverse audiences.",
    photoUrl: "/images/Nana Ama.webp",
    photoUrlModal: "/images/Nana Ama modal.webp",
    email: "",
    socialLinks: { linkedin: "https://linkedin.com" },
    department: "General Management",
    order: 2,
  },
  {
    name: "Nicholson Eben Atsoribo",
    title: "Agronomist & Operations",
    location: "Accra, Ghana",
    bio: "Nicholson is an agronomist and operations specialist with extensive experience in agricultural research and development. He has led multiple projects in crop management, soil health, and sustainable farming practices.",
    photoUrl: "/images/Nicholson Eben Atsoribo.webp",
    photoUrlModal: "/images/Nicholson Eben Atsoribo modal.webp",
    email: "",
    socialLinks: { linkedin: "https://linkedin.com" },
    department: "Operations Management",
    order: 4,
  },
  {
    name: "Nancy Otibo Tamakoe",
    title: "Strategic Advisor, Soil & Crop",
    hoverTitle: "Advisor",
    location: "Accra, Ghana",
    bio: "Nancy is a strategic advisor specializing in soil and crop management. She brings deep expertise in sustainable agriculture and has led initiatives to improve soil health and crop yields across various farming systems.",
    photoUrl: "/images/Nancy Otibo Tamakoe .webp",
    photoUrlModal: "/images/Nancy Otibo Tamakoe modal.webp",
    email: "",
    socialLinks: { linkedin: "https://linkedin.com" },
    department: "Strategic Advisors",
    order: 7,
  },
  {
    name: "Jacob Korley",
    title: "Accounts Officer",
    location: "Accra, Ghana",
    bio: "Jacob is an experienced accounts officer with a strong background in financial management and accounting. He has successfully managed financial operations for various organizations, ensuring compliance and accuracy in all financial reporting.",
    photoUrl: "/images/Jacob Korley .webp",
    photoUrlModal: "/images/Jacob Korley modal.webp",
    email: "",
    socialLinks: { linkedin: "https://linkedin.com" },
    department: "Operations Management",
    order: 6,
  },
];
